### PR TITLE
Feature/86 fix minmeanmax transform

### PR DESCRIPTION
**Pull request by CFlaniganMide**
Fixes an issue where the method `arrayMinMeanMax` wasn't using calibrated data, as well as some other issues that cropped up involving `PolyPoly` transforms.

### CODE REVIEW

**Comment by CFlaniganMide** [comment]
Well, python on windows 3.7 is passing which, coincidentally, is my dev environment.  Will open this back up once I figure out what the hell is happening.

**Review by StokesMIDE — COMMENTED** [review]
I get a failure trying to use the test file `testing/test3.ide`:
```python
doc = importFile('testing/test3.ide')
x = doc.channels[8][0].getSession()
x.getRangeMinMeanMax()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\dstokes\workspace\idelib\idelib\dataset.py", line 3211, in getRangeMinMeanMax
    display=display, iterator=iterator)
  File "C:\Users\dstokes\workspace\idelib\idelib\dataset.py", line 2071, in arrayMinMeanMax
    out[0, idx, i] = xform(t, _min)[1]
  File "C:\Users\dstokes\workspace\idelib\idelib\transforms.py", line 501, in __call__
    channel = self.dataset.channels[self.channelId][self.subchannelId]
KeyError: None
```
Is this not a valid file? It seems like we should be using actual files for tests, and maybe generate a more descriptive exception if this might happen in the wild.

**Comment by CFlaniganMide** [comment]
> 
> 
> > I get a failure trying to use the test file `testing/test3.ide`:
> > ```python
> > doc = importFile('testing/test3.ide')
> > x = doc.channels[8][0].getSession()
> > x.getRangeMinMeanMax()
> > Traceback (most recent call last):
> >   File "<input>", line 1, in <module>
> >   File "C:\Users\dstokes\workspace\idelib\idelib\dataset.py", line 3211, in getRangeMinMeanMax
> >     display=display, iterator=iterator)
> >   File "C:\Users\dstokes\workspace\idelib\idelib\dataset.py", line 2071, in arrayMinMeanMax
> >     out[0, idx, i] = xform(t, _min)[1]
> >   File "C:\Users\dstokes\workspace\idelib\idelib\transforms.py", line 501, in __call__
> >     channel = self.dataset.channels[self.channelId][self.subchannelId]
> > KeyError: None
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is this not a valid file? It seems like we should be using actual files for tests, and maybe generate a more descriptive exception if this might happen in the wild.
> 
> I don't really remember if it's a valid file, but I'll check it out. This definitely turned out to be a more complex problem than anticipated.

Looking at this a little bit closer, it looks like this is from the branch `hotfix/minmeanmax` and not `feature/86_fix_minmeanmax`, but the problem would probably be the same.  Either way, I don't have the file `test3.ide` but it does look like there's a key error being thrown because the file is messed up.

**Comment by StokesMIDE** [comment]
> Looking at this a little bit closer, it looks like this is from the branch `hotfix/minmeanmax` and not `feature/86_fix_minmeanmax`, but the problem would probably be the same. 

You are correct; I was using the wrong branch. The correct one does not raise an exception.

> Either way, I don't have the file `test3.ide` but it does look like there's a key error being thrown because the file is messed up.

The file [`test3.ide`](https://github.com/MideTechnology/idelib/blob/feature/86_fix_minmeanmax_transform/testing/test3.IDE) is in the `testing` directory.

**Review by StokesMIDE — APPROVED** [review]
My testing wasn't very scientific, but it looks like it works! If no one else requests changes, I think it's good to go.

**Pull request merged**
