### PR TITLE
Remove eventlist

### PR DESCRIPTION
**Pull request by CrepeGoat**
This is what I think it would look like to remove `EventList` from the code.

AFAIK, there should be no behavioral changes in `EventArray` resulting from this PR. It's possible that we may want to swap out `EventArray.getBlockRollingMean` with the `EventList` implementation, but that can go in another PR I think.

Anyway, this is a remarkably easy change that I think makes the code overall a lot cleaner. I'd like to get this pushed through if possible.

### CODE REVIEW

**Comment by StokesMIDE** [comment]
What about the importer? That is where things got convoluted. With only one class of event data, its implementation should follow the same pattern as the other importers: one parser class named for the element itself (ChannelDataBlock), and one 'data block' implementation.

**Review by StokesMIDE — CHANGES_REQUESTED** [review]
The pattern is for the names to match the elements. Don't rename `ChannelDataBlock`.

**Comment by CrepeGoat** [comment]
> The pattern is for the names to match the elements. Don't rename `ChannelDataBlock`.

I... don't understand what you're trying to say.

1. I didn't "rename" anything; I removed `ChannelDataBlock` entirely; whatever was working with the old naming scheme should (and by the test report, *is*) still working.
2. The only place I can see the `ChannelDataBlock` name being used is [here](https://github.com/MideTechnology/idelib/blob/main/idelib/importer.py#L440), and it converts `"ChannelDataBlock"` into `"ChannelDataArrayBlock"`. AFAI understand, the `"ChannelDataBlock"` name is coming from the schema? And IIRC the conversion at the above-referenced line was a workaround to accommodate `ChannelDataArrayBlock` back when we added it. So there should be no reliance on the `ChannelDataBlock` class in the importer, or anywhere else... right?

**Comment by CFlaniganMide** [comment]
I think it ties into the comment I left.  The name `ChannelDataArrayBlock` was a workaround and required us to do stuff that broke our pattern.  It would be cleaner to keep the name `ChannelDataBlock` by removing the old implementation and renaming `ChannelDataArrayBlock`

**Comment by CrepeGoat** [comment]
> It would be cleaner to keep the name `ChannelDataBlock` by removing the old implementation and renaming `ChannelDataArrayBlock`

oh. I mean yeah, that sounds much cleaner and we should definitely do that.

> I think it ties into the comment I left.

did I miss that? was that on this PR or somewhere else?

**Review by CFlaniganMide — APPROVED** [review]
after the names were changed, I think this is good to go.

**Review by StokesMIDE — APPROVED** [review]

**Pull request merged**
