### PR TITLE
ES-223: Implement SubChannelVisibility feature

### PR DESCRIPTION
**Pull request by StokesMIDE**
This adds parsing of the `<SubChannelVisibility>` element, and the ability to filter the results of `Dataset.getPlots()` (used by enDAQ Lab to retrieve the subchannels to draw) by visibility level. By default, anything with a visibility level greater than zero is excluded.

Without additional changes to enDAQ Lab, this will hide all channels we mark as 'invisible,' but with no mechanism for displaying them. Future versions of enDAQ Lab will make a range of the invisible subchannels (e.g., GPS time and other data meaningful to a human user) available in the 'View->Display Channels' submenu. An 'advanced option' will make it possible to display any invisible channel (e.g., diagnostic data, the plot of which is largely meaningless).

### CODE REVIEW

**Comment by pscheidler** [comment]
I plan to approve but 1 questions before this gets merged in and falls off my radar:
 - Will users be able to export the data, even though they can't see it in a plot?

**Comment by StokesMIDE** [comment]
>     * Will users be able to export the data, even though they can't see it in a plot?

As currently implemented in enDAQ Lab, all channels should appear in the export dialog, since that list is built from a different source - directly from the channel list, not `getPlots()`. A future version might have some of the more technical/diagnostic channels hidden unless a 'show advanced' option is checked.

**Review by tgipsonMIDE — APPROVED** [review]
Looks good to me! Quick caveat though, all of the time correlation (etc.) channels written by the device currently have visibility +50. If we want them to be +1 going forward it's an easy change, we'll just have to update the FW and docs to reflect it.

**Comment by StokesMIDE** [comment]
> Looks good to me! Quick caveat though, all of the time correlation (etc.) channels written by the device currently have visibility +50. If we want them to be +1 going forward it's an easy change, we'll just have to update the FW and docs to reflect it.

@tgipsonMIDE I'm happy to do whatever scale/range, and it's trivial for me to change things on my end. I dug out a proposed range; does it look like what you'd planned?

    0: Always visible (default)

    10: Optionally visible, things probably of interest to the user in certain situations

    20: Hide by default, but possibly of use to the user

    30: Hide by default, channel used indirectly (but human readable)

    40: Hide by default, channel used indirectly (not very human readable)

    50: Diagnostic, always hide. Accessible via the idelib API.

**Review by tgipsonMIDE — APPROVED** [review]

**Pull request merged**
