### PR TITLE
Hotfix/missing transform fix

### PR DESCRIPTION
**Pull request by CFlaniganMide**
This is a hotfix for the issue Steve found.   The issue is basically caused by `CombinedPoly` objects where all polynomials are `None`.

### CODE REVIEW

**Review by StokesMIDE — DISMISSED** [review]

**Comment by CrepeGoat** [comment]
did you test this on the file Steve was finding errors on?

**Comment by CFlaniganMide** [comment]
> 
> 
> @CFlaniganMide did you test this on the file Steve was finding errors on?

yeah, the issue had to do with accessing the GPS data, and after applying the fix it's able to get and graph it.

**Comment by CFlaniganMide** [comment]
ignore that close, I hit the wrong button.

**Review by CrepeGoat — APPROVED** [review]
Looks good, as long as the original file generating the error was tested against (and Connor said it was)

**Comment by CrepeGoat** [comment]
...actually wait. are we incrementing version numbers in this PR?

**Comment by CFlaniganMide** [comment]
the hotfix will be a new release, yeah

**Comment by CrepeGoat** [comment]
ahhh I didn't see aa26dd439eb47c9350b09195ee936162d8ca2de3; all good!

**Pull request merged**
