### PR TITLE
Release/3.2.0

### PR DESCRIPTION
**Pull request by CFlaniganMide**
- **Enhancement:** Improved in-memory caching performance.
- **Enhancement:** `idelib.importer.importFile()` and `idelib.importer.readData()` now have `startTime`, `endTime`, and `channels` arguments for selectively importing only specific time ranges or channels.
- **Enhancement:** `repr` for `idelib.dataset.Channel`, `idelib.dataset.SubChannel`, and `idelib.dataset.EventArray` has been improved to show more information.
- **Enhancement:** New Utility Functions:
  - `idelib.util.extractTime()`: saves a portion of an IDE to another IDE.
  - `idelib.util.getLength()`: Efficiently gets the estimated start and end times of an IDE file without importing it. Replaces the previous, less accurate version in `idelib.importer`.
  - `idelib.util.getExitCondition()`: Gets the 'exit condition' of a file (what caused the device to stop recording). Replaces the less effective version in `idelib.importer`.
- **Maintenance:** Consolidated class `EventList` into `EventArray`.
- **Maintenance:** Refactored tests.
- **Deprecation:** Removed rolling-mean-removal.
- **Documentation:** Added Sphinx documentation with doctests.

### CODE REVIEW

**Comment by StokesMIDE** [comment]
We should probably do release notes, with a high-level overview of salient changes.

**Comment by CFlaniganMide** [comment]
> 
> 
> We should probably do release notes, with a high-level overview of salient changes.

I agree.  Can you and @CrepeGoat summarize your changes, I'll do mine, and then we'll collate the lists?

**Comment by CFlaniganMide** [comment]
I'm going to edit this comment with the changelog, and copy it to the release page.

- **Enhancement:** Improved in-memory caching performance.
- **Deprecation:** Removed rolling-mean-removal.

**Comment by CrepeGoat** [comment]
changelog stuff:
- (basic maintenance) consolidated class `EventList` into `EventArray`
- added Sphinx documentation w/ doctests
- (maintenance) refactored tests

**Review by CrepeGoat — APPROVED** [review]
I don't think there's anything I can do, or ask other to do, to make this more ready than it is atm -> looks good

**Comment by StokesMIDE** [comment]
* Enhancement: `idelib.importer.importFile()` and `idelib.importer.readData()` now have `startTime`, `endTime`, and `channels` arguments for selectively importing only specific time ranges or channels.
* Enhancement: `repr` for `idelib.dataset.Channel` and `idelib.dataset.SubChannel` has been improved to show more information.
* Enhancement: New utility functions:
  * `idelib.util.extractTime()`: saves a portion of an IDE to another IDE.
  * `idelib.util.getLength()`: Efficiently gets the estimated start and end times of an IDE file without importing it. Replaces the previous, less accurate version in `idelib.importer`.
  * `idelib.util.getExitCondition()`: Gets the 'exit condition' of a file (what caused the device to stop recording). Replaces the less effective version in `idelib.importer`.

**Review by StokesMIDE — APPROVED** [review]
Release note items in previous comment.

**Pull request merged**
